<a href="https://colab.research.google.com/github/ashkanmulla/Python/blob/main/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
l1 = [1,2,3,4]

In [3]:
n1 = np.array(l1)

In [4]:
type(n1)

numpy.ndarray

In [5]:
n2 = np.array([[1,2,3,4],[4,3,2,1]])

In [6]:
n2

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [7]:
type(n2)

numpy.ndarray

In [8]:
# Initializing Numpy array with zero

In [9]:
import numpy as np

In [10]:
n1 = np.zeros((1,2))

In [11]:
n1

array([[0., 0.]])

In [12]:
n1 = np.zeros((5,5))

In [13]:
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
n3 = np.zeros((2,3))

In [15]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
n4 = np.zeros((10,10))

In [17]:
n4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
#Initializing Numpy array with same number

In [19]:
n5 = np.full((3,3),55)

In [20]:
n5

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [21]:
 #Initializing Numpy array within a range

In [22]:
n6 = np.arange(10,20)

In [23]:
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
import numpy as np

In [25]:
n1 = np.arange(50,200,2)

In [26]:
n1

array([ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,
        76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100,
       102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126,
       128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152,
       154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178,
       180, 182, 184, 186, 188, 190, 192, 194, 196, 198])

In [27]:
#Initializing Numpy array with random number

In [28]:
import numpy as np

In [29]:
n1 = np.random.randint(1,5)

In [30]:
n1

3

In [31]:
n1 = np.random.randint(1,100,5)

In [32]:
n1

array([55,  8,  2, 46, 23])

In [33]:
#Checking & changing the shape of Numpy arrays

In [34]:
import numpy as np

In [35]:
n1 = np.array([[1,2,3],[4,5,6]])

In [36]:
n1

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
n1.shape

(2, 3)

In [38]:
n1.shape = (3,2)

In [39]:
n1.shape

(3, 2)

In [40]:
import numpy as np

In [41]:
n7 = np.array([[1,2,3,4,5],[5,4,3,2,1]])

In [42]:
n7

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [43]:
#Joining Numpy Arrays (Vertical , Horizontal and Column Stack)

In [44]:
import numpy as np

In [45]:
n1 = np.array([1,2,3])

In [46]:
n2 = np.array([4,5,6])

In [47]:
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [49]:
np.column_stack((n1,n2)) #Remember

array([[1, 4],
       [2, 5],
       [3, 6]])

In [50]:
#Intersection & Difference #(n1 - n2)this is for difference only

In [51]:
import numpy as np

In [52]:
n1 = np.array([10,20,30,40,50,60])

In [53]:
n2 = np.array([50,60,70,80,90])

In [54]:
np.intersect1d(n1,n2)

array([50, 60])

In [55]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [56]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [57]:
#Adding of Numpy array

In [58]:
import numpy as np

In [59]:
n1 = np.array([10,20])

In [60]:
n2 = np.array([30,40])

In [61]:
np.sum([n1,n2])

100

In [62]:
np.sum([n1,n2],axis = 0)

array([40, 60])

In [63]:
np.sum([n1,n2],axis = 1)

array([30, 70])

In [64]:
#Numpy Array Basic Marhematics

In [65]:
n1 = np.array([10,20,30])

In [66]:
n1

array([10, 20, 30])

In [67]:
n1 + 5

array([15, 25, 35])

In [68]:
n1 - 5

array([ 5, 15, 25])

In [69]:
n1 * 5

array([ 50, 100, 150])

In [70]:
n1 / 5

array([2., 4., 6.])

In [71]:
n1 // 5

array([2, 4, 6])

In [72]:
#Numpy Maths Functions

In [73]:
import numpy as np

In [74]:
n1 = np.random.randint(1,50,10)

In [75]:
n1

array([32, 43, 36,  5, 23, 41, 20, 13,  1,  6])

In [76]:
np.mean(n1)

22.0

In [77]:
np.median(n1)

21.5

In [78]:
np.std(n1)

14.730919862656235

In [79]:
#Numpy Save and Load

In [80]:
n1

array([32, 43, 36,  5, 23, 41, 20, 13,  1,  6])

In [81]:
np.save("my_array",n1)

In [82]:
new_n1 = np.load("my_array.npy")

In [83]:
new_n1

array([32, 43, 36,  5, 23, 41, 20, 13,  1,  6])